# Generated by Django 4.2 on 2026-01-08 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alpinist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Climb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_planned', models.DateTimeField(verbose_name='Начало (план)')),
                ('end_planned', models.DateTimeField(verbose_name='Завершение (план)')),
                ('start_actual', models.DateTimeField(blank=True, null=True, verbose_name='Начало (факт)')),
                ('end_actual', models.DateTimeField(blank=True, null=True, verbose_name='Завершение (факт)')),
                ('group_name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('is_group_success', models.BooleanField(default=False, verbose_name='Успех группы')),
                ('group_notes', models.TextField(blank=True, verbose_name='Пояснение о группе (нештатные ситуации)')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название клуба')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=150, verbose_name='Контактное лицо')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название горы')),
                ('height', models.PositiveIntegerField(verbose_name='Высота (метры)')),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100, verbose_name='Район')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание маршрута')),
                ('expected_duration', models.DurationField(verbose_name='Продолжительность (план)')),
                ('mountain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='climbing_app.mountain')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_success', models.BooleanField(default=False, verbose_name='Успех участника')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failed', 'Не успешно'), ('injury', 'Травма'), ('missing', 'Пропал без вести'), ('fatal', 'Летальный исход'), ('other', 'Другое')], default='success', max_length=20, verbose_name='Состояние')),
                ('incident_details', models.TextField(blank=True, verbose_name='Подробности нештатной ситуации')),
                ('alpinist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='climbing_app.alpinist')),
                ('climb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='climbing_app.climb')),
            ],
        ),
        migrations.AddField(
            model_name='climb',
            name='participants',
            field=models.ManyToManyField(related_name='climbs', through='climbing_app.Participation', to='climbing_app.alpinist'),
        ),
        migrations.AddField(
            model_name='climb',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='climbing_app.route'),
        ),
        migrations.AddField(
            model_name='alpinist',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='climbing_app.club'),
        ),
    ]
