# Generated by Django 4.2 on 2026-02-26 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mountain',
            options={'ordering': ['id']},
        ),
    ]
