# Generated by Django 4.2 on 2026-02-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbing_app', '0002_alter_mountain_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alpinist',
            name='club',
        ),
        migrations.AddField(
            model_name='alpinist',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='members', to='climbing_app.club', verbose_name='Клубы'),
        ),
    ]
