services:
  db:
    image: postgres:15-alpine
    container_name: climbing_db_cont
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=climbing_db
      - POSTGRES_USER=climbing_user
      - POSTGRES_PASSWORD=climbing_pass

  web:
    build: .
    container_name: climbing_web_cont
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8010:8000"
    environment:
      - DB_NAME=climbing_db
      - DB_USER=climbing_user
      - DB_PASS=climbing_pass
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  frontend:
    build: ./climbing-frontend 
    container_name: climbing_vue_cont
    ports:
      - "5173:5173"
    volumes:
      - ./climbing-frontend:/app
      - /app/node_modules 
    depends_on:
      - web

volumes:
  postgres_data:
