services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=race_db
      - POSTGRES_USER=race_user
      - POSTGRES_PASSWORD=race_password

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=race_db
      - DATABASE_USER=race_user
      - DATABASE_PASSWORD=race_password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data: