# Generated by Django 3.2.25 on 2025-12-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='racer_class',
            field=models.CharField(choices=[('A', 'Класс A'), ('B', 'Класс B'), ('C', 'Класс C')], default='C', max_length=10, verbose_name='Класс'),
        ),
    ]
